### ISSUE TITLE
Plugins using inotify

### ISSUE THREAD

**Issue by jeremija** [j4tools/j4status-plugins#6]
Hi there! I created two plugins which use `inotify` and I would like to push them here when I'm done. I'm not sure what's the policy about that because `inotify` is linux-only - I see most plugins use glib's functions so I assume that's because of portability.

I realize I could've used `g_file_monitor_file` (like the `file-monitor` plugin does) as it should use `inotify` under the hood on linux, however I was unhappy with the 1 second delay it adds, and the function `g_file_monitor_set_rate_limit` doesn't do anything for me. [This old thread](https://www.mail-archive.com/gtk-devel-list@gnome.org/msg11840.html) was the only discussion I could find about it, and it doesn't seem anything has changed in the meantime.

So my question is: would adding a linux-only plugin be acceptable? If so, are there any rules I should follow, like make the plugin disabled by default? Or we assume most people who use these plugins are already on linux so it doesn't really matter?

**Comment by sardemff7** [comment]
I do not see a problem for Linux-only plugins in general. I do prefer people to use the GLib stuff when possible because it can work even on Windows!

Just make sure you have the correct checks (not as in “`AS_CASE([$host])` checks” but as in “`AC_CHECK_HEADERS([linux/stuff.h], [], [AC_MSG_ERROR([linux/stuff.h required for plugin foo])])`).

If you go the GLib way, you may have a look at [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=739322) and why not try to provide a patch! The inotify code of GIO is old and since you already dug in intofiy, that could help.

**Comment by jeremija** [comment]
Thanks for the comments, I understand!

Interesting that you mentioned this bug. It seems somebody has already tackled this problem in GNOME/glib@779c809. Based on the git history, it seems this functionality is in GLib 2.45.1, however 2.45 is still a development branch.

I will then continue to use `inotify` and plan to switch to GLib's file monitor after GLib 2.45 becomes stable.

**Comment by sardemff7** [comment]
This means GLib 2.46 (odd = dev, even = stable). Nice.

Depending on how your code is designed, you can try to keep the inotify support around after the GLib release, for older systems.
Please note that:
1. j4status 0.1 requires GLib 2.28
2. j4status 0.2 will require GLib 2.40 (bumped in sardemff7/j4status@539dad574ce0d86e2dd2f95042d0707349358232)
3. the input plugin API didn’t change since j4status 0.1
4. Debian stable has GLib 2.42, the latest Ubuntu LTS has 2.40, Debian oldstable has 2.33
